apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: valida-senha
  name: valida-senha
spec:
  replicas: 2
  selector:
    matchLabels:
      app: valida-senha
  template:
    metadata:
      labels:
        app: valida-senha
    spec:
      containers:
        - image: robsonrossan/valida-senha:v1
          name: valida-senha
---   
apiVersion: v1
kind: Service
metadata:
 labels:
   app: valida-senha
 name: valida-senha
spec:
  type: LoadBalancer
  ports:
  - name: "valida-senha-service"
    port: 8080
    targetPort: 8080
  selector:
    app: valida-senha        